apiVersion: apps/v1
kind: Deployment
metadata:
  name:
  labels:
    app: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello-app
          image: vaggelas/file-server-application:42.0
          ports:
            - containerPort: 8080
