apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hello-app
  labels:
    app: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello-app
          image: vaggelas/mancala:1.0
          ports:
            - containerPort: 8080

  strategy:
    blueGreen:
      activeService: hello-app
      previewService: hello-app-preview
      scaleDownDelaySeconds: 60 # 1 minute
  #    postPromotionAnalysis:
  #      templates:
  #        - templateName: smoke-tests
  #      args:
  #        - name: service-name
  #          value: preview-svc.default.svc.cluster.local